{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ include "postgres.postgresPassword" . | b64enc | quote }}
  password: {{ include "postgres.password" . | b64enc | quote }}
  username: {{ .Values.auth.username | b64enc | quote }}
  database: {{ .Values.auth.database | b64enc | quote }}
{{- end }}
