{{- if not .Values.synapse.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.secretName" . }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.database.existingSecret }}
  POSTGRES_PASSWORD: {{ include "matrix.postgresPassword" . | b64enc | quote }}
  {{- end }}
  REGISTRATION_SHARED_SECRET: {{ include "matrix.registrationSharedSecret" . | b64enc | quote }}
  MACAROON_SECRET_KEY: {{ include "matrix.macaroonSecretKey" . | b64enc | quote }}
  FORM_SECRET: {{ include "matrix.formSecret" . | b64enc | quote }}
{{- end }}
